#!/usr/bin/env bash
# Wrapper invoked by launchd. Runs each personal-automation app in order and posts a
# macOS notification on any non-zero exit so failures don't go unseen.
#
# Add new apps by appending to APPS below; they'll run in sequence.

set -u
# Guarded twice: a failed substitution leaves PROJECT_DIR empty, and `cd ""` is a no-op that would
# run pnpm from launchd's own directory. Both the exit code and the shell's message reach the logs.
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)" || exit 1
cd "$PROJECT_DIR" || exit 1

# Both YNAB apps are paused. Amazon stopped putting product names in its order
# emails (only a generic category like "1 Beverages item" remains), so
# enrich-memos can only write useless labels and ynab-categorize mis-categorizes
# on them. Re-enable (enrich first, so ynab-categorize sees populated memos)
# once a reliable line-item source exists. See amazon-item-data.progress.local.md.
APPS=(
  # 'ynab-enrich-memos'
  # 'ynab-categorize'
)
# tasks is NOT here: it has its own launchd agent (com.personal-automation.tasks)
# on the TASKS_SCHEDULE days/times, generated by setup.sh.

err_log="$(mktemp -t personal-automation.XXXXXX)"
trap 'rm -f "$err_log"' EXIT

overall_exit=0
# Guard the empty case: under `set -u`, expanding an empty array errors on bash 3.2.
if [ "${#APPS[@]}" -gt 0 ]; then
  for app in "${APPS[@]}"; do
    /bin/zsh -lc "pnpm --filter @personal-automation/$app $app" 2> >(tee -a "$err_log" >&2)
    app_exit=$?
    if [ "$app_exit" -ne 0 ]; then
      overall_exit=$app_exit
      # Don't bail on the first failure; let later apps still run.
    fi
  done
fi

# Always invoke notify. It reads today's audit logs and decides whether to send.
# `|| true` so a notify failure doesn't poison $overall_exit. No exit-code gating:
# $overall_exit is the last non-zero app exit, so gating on a specific value could
# mask real failures from another app in the same run.
/bin/zsh -lc "pnpm --filter @personal-automation/notify notify" || true

# Trim audit + run-log JSONL older than 90 days so those dirs don't grow forever.
find "$PROJECT_DIR/apps"/*/audit "$PROJECT_DIR/apps"/*/runs -name '*.jsonl' -mtime +90 -delete 2>/dev/null || true

if [ "$overall_exit" -ne 0 ]; then
  last_err="$(tail -3 "$err_log" | tr '\n' ' ' | sed 's/"/\\"/g')"
  /usr/bin/osascript \
    -e "display notification \"${last_err:-See $PROJECT_DIR/launchd/logs/daily.err.log}\" with title \"Personal Automation FAILED (exit $overall_exit)\" sound name \"Basso\""
fi

exit "$overall_exit"
